steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    id: Push
  - name: "gcr.io/google-appengine/exec-wrapper"
    args: ["-i", "${_GCR_HOSTNAME}:/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}",
           "-s", "${PROJECT_ID}:${_REGION}:myinstance",
           "--", "python", "manage.py", "migrate"]
  - name: "gcr.io/google-appengine/exec-wrapper"
    args: ["-i", "${_GCR_HOSTNAME}:/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}",
           "-s", "${PROJECT_ID}:${_REGION}:myinstance",
           "--", "python", "manage.py", "collectstatic", "--no-input"]    
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: smallshop-dev
  _LABELS: gcb-trigger-id=be664d4d-30a7-42b0-978a-740a4a7b8a67
  _TRIGGER_ID: be664d4d-30a7-42b0-978a-740a4a7b8a67
  _DEPLOY_REGION: europe-west1
  _GCR_HOSTNAME: eu.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - smallshop-dev
